import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';
import { extname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import {
  buildPublicCaptionFromPrompt,
  decideAutoStage,
} from '../../src/lib/aiCastExperience';
import { creatorRenderStateCopy } from '../../src/lib/renderStateCopy';
import { detectModerationCategories } from '../src/services/moderationOrchestrator';
import { sanitizeProviderPrompt } from '../src/services/providerPromptSanitizer';
import {
  normalizedDurationSeconds,
  validateSeedanceProviderPayload,
} from '../src/services/providers/seedanceProvider';

const benignPrompt =
  'She smiles gently, turns toward the sunlight, and gives a small wave. Natural movement, steady camera, soft daylight.';

const route = decideAutoStage({
  hasPrompt: true,
  explicitDemoMode: false,
  exactLikenessReady: false,
  selfCharacterReady: true,
  userPrompt: benignPrompt,
});
assert.equal(route.engine, 'seedance-2.0');
assert.equal(route.route, 'director_primary');
assert.equal(route.fallbackEngine, null);

const moderationCategories = detectModerationCategories({
  prompt: benignPrompt,
  referenceImageCount: 0,
});
assert.deepEqual(moderationCategories, []);

const sanitized = sanitizeProviderPrompt({ prompt: benignPrompt });
assert.equal(sanitized.prompt, benignPrompt);
assert.equal(sanitized.changed, false);
assert.deepEqual(sanitized.riskyTermsRemoved, []);
assert.deepEqual(sanitized.socialPhrasesRemoved, []);
assert.deepEqual(sanitized.artifactsRemoved, []);
assert.equal(normalizedDurationSeconds(4), 4);
assert.equal(validateSeedanceProviderPayload({
  prompt: benignPrompt,
  duration: 4,
  aspect_ratio: '9:16',
  resolution: '480p',
  generate_audio: false,
}).ok, true);

assert.equal(
  buildPublicCaptionFromPrompt(benignPrompt),
  'She smiles gently, turns toward the sunlight, and gives a small wave.',
);

assert.match(creatorRenderStateCopy('failed').body, /technical problem/i);
assert.match(creatorRenderStateCopy('blocked').body, /account or renderer setup/i);
assert.match(creatorRenderStateCopy('paused').body, /simpler direction/i);
assert.equal(creatorRenderStateCopy('paused').primaryActionLabel, 'Use safer scene idea');

const createSource = readFileSync(join(process.cwd(), 'src/components/CreateVideo.tsx'), 'utf8');
assert.match(
  createSource,
  /selectedEngine === 'replicate'\s*\?\s*polishKlingCinematicPrompt\(userPrompt\)\s*:\s*\{ prompt: userPrompt/,
);
assert.match(createSource, /resolution: '480p'/);
assert.match(createSource, /generateAudio: false/);
assert.match(createSource, /maxProviderRequests: 1/);
assert.match(createSource, /function handleUseSaferSceneIdea\(\)/);
const saferSceneHandler = createSource.match(
  /function handleUseSaferSceneIdea\(\) \{([\s\S]*?)\n  \}\n\n  async function handleUseIdentityOnlyKlingFallback/,
)?.[1] ?? '';
assert.match(saferSceneHandler, /setActivePrompt\(ULTRA_SAFE_SCENE_PROMPT\)/);
assert.match(saferSceneHandler, /Review it, then tap Generate/);
assert.doesNotMatch(saferSceneHandler, /handleGenerate\(/);

const seedanceEntry = readFileSync(
  join(process.cwd(), 'serverless/entries/generations-seedance.ts'),
  'utf8',
);
assert.match(seedanceEntry, /aspectRatio: aspectRatioValue\(body\.aspectRatio\)/);
assert.match(seedanceEntry, /generateAudio: booleanValue\(body\.generateAudio\)/);
assert.match(seedanceEntry, /maxProviderRequests: maxProviderRequestsValue\(body\.maxProviderRequests\)/);

const seedanceProviderSource = readFileSync(
  join(process.cwd(), 'backend/src/services/providers/seedanceProvider.ts'),
  'utf8',
);
assert.match(seedanceProviderSource, /allowPaidCreateRetry: options\.maxProviderAttempts !== 1/);
assert.match(seedanceProviderSource, /input\.allowPaidCreateRetry/);

const seedanceBundle = readFileSync(
  join(process.cwd(), 'api/generations/seedance.js'),
  'utf8',
);
assert.match(seedanceBundle, /Generated by scripts\/build-vercel-api\.mjs/);
assert.match(seedanceBundle, /function checkRateLimit/);
assert.match(seedanceBundle, /async function createSeedanceGeneration/);
assert.doesNotMatch(seedanceBundle, /from\s+["'][^"']*serverless\/_lib\/rateLimit/);
assert.doesNotMatch(seedanceBundle, /from\s+["'][^"']*backend\/src/);

const { default: seedanceHandler } = await import(
  `${pathToFileURL(join(process.cwd(), 'api/generations/seedance.js')).href}?test=${Date.now()}`
);
const responseHeaders = new Map<string, string>();
let responseStatus = 0;
let responseBody = '';
await seedanceHandler(
  { method: 'GET' },
  {
    set statusCode(value: number) {
      responseStatus = value;
    },
    get statusCode() {
      return responseStatus;
    },
    setHeader(name: string, value: string) {
      responseHeaders.set(name, value);
    },
    end(value: string) {
      responseBody = value;
    },
  },
);
assert.equal(responseStatus, 405);
assert.equal(responseHeaders.get('Allow'), 'POST');
assert.equal(JSON.parse(responseBody).error, 'Method not allowed');

function apiEndpointFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolutePath = join(directory, entry.name);
    if (entry.isDirectory()) return apiEndpointFiles(absolutePath);
    return ['.ts', '.js'].includes(extname(entry.name)) ? [absolutePath] : [];
  });
}

assert.equal(apiEndpointFiles(join(process.cwd(), 'api')).length, 12);

console.log('real render canary regression tests passed');
