// Generated by scripts/build-vercel-api.mjs. Do not edit by hand.

// backend/src/lib/env.ts
import "dotenv/config";
import { z } from "zod";
var booleanEnv = z.preprocess((value) => {
  if (typeof value === "boolean") return value;
  if (typeof value === "number") return value === 1;
  if (typeof value === "string") {
    const normalized = value.trim().toLowerCase();
    if (["1", "true", "yes", "y", "on"].includes(normalized)) return true;
    if (["0", "false", "no", "n", "off", ""].includes(normalized)) return false;
  }
  return value;
}, z.boolean());
var envSchema = z.object({
  API_PORT: z.coerce.number().default(8787),
  APP_URL: z.string().url().default("http://localhost:4173"),
  WEB_ORIGIN: z.string().optional(),
  DEMO_MODE: booleanEnv.default(false),
  BILLING_ENABLED: booleanEnv.default(false),
  REQUIRE_STRIPE: booleanEnv.default(false),
  SUPABASE_URL: z.string().url().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(1).optional(),
  SUPABASE_JWT_SECRET: z.string().min(1).optional(),
  DATABASE_URL: z.string().min(1).optional(),
  REDIS_URL: z.string().min(1).optional(),
  STRIPE_SECRET_KEY: z.string().min(1).optional(),
  STRIPE_WEBHOOK_SECRET: z.string().min(1).optional(),
  OPENAI_API_KEY: z.string().min(1).optional(),
  OPENAI_MODEL: z.string().min(1).optional(),
  OPENAI_CHAT_MODEL: z.string().min(1).optional(),
  OPENAI_IMAGE_MODEL: z.string().default("gpt-image-1"),
  OPENAI_VIDEO_ENABLED: booleanEnv.default(false),
  OPENAI_VIDEO_MODEL: z.string().default("sora-2"),
  OPENAI_VIDEO_CHARACTER_ENABLED: booleanEnv.default(false),
  OPENAI_VIDEO_SIZE: z.string().default("720x1280"),
  OPENAI_VIDEO_SECONDS: z.coerce.number().int().refine((value) => [4, 8, 12].includes(value), {
    message: "OPENAI_VIDEO_SECONDS must be 4, 8, or 12."
  }).default(4),
  DEBUG_PROVIDER_PROMPTS: booleanEnv.default(false),
  GOOGLE_API_KEY: z.string().min(1).optional(),
  FAL_ADMIN_KEY: z.string().min(1).optional(),
  FAL_KEY: z.string().min(1).optional(),
  KLING_ENABLED: booleanEnv.default(false),
  KLING_PROVIDER: z.string().default("fal"),
  KLING_API_KEY: z.string().min(1).optional(),
  KLING_MODEL: z.string().min(1).optional(),
  KLING_REFERENCE_MODEL: z.string().min(1).default("fal-ai/kling-video/o1/standard/reference-to-video"),
  KLING_ELEMENTS_MODEL: z.string().min(1).optional(),
  KLING_SCENE_ANCHOR_VIDEO_MODEL: z.string().min(1).optional(),
  SCENE_ANCHOR_ENABLED: booleanEnv.default(false),
  SCENE_ANCHOR_PROVIDER: z.string().default("fal"),
  SCENE_ANCHOR_MODEL: z.string().min(1).optional(),
  SCENE_ANCHOR_FALLBACK_MODE: z.string().default("pause"),
  RUNWAY_ENABLED: booleanEnv.default(false),
  RUNWAY_API_KEY: z.string().min(1).optional(),
  RUNWAY_MODEL: z.string().min(1).optional(),
  RUNWAY_REFERENCE_MODEL: z.string().min(1).optional(),
  REPLICATE_API_TOKEN: z.string().min(1).optional(),
  REPLICATE_WEBHOOK_SECRET: z.string().min(1).optional(),
  RENDER_SUCCESS_MAX_PAID_ATTEMPTS: z.coerce.number().int().min(1).max(5).default(3),
  RENDER_SUCCESS_AUTO_RETRY: booleanEnv.default(true),
  ENABLE_RENDER_PROBE: booleanEnv.default(false),
  RESEND_API_KEY: z.string().min(1).optional(),
  NOTIFICATION_FROM: z.string().email().default("alerts@example.com")
});
var env = envSchema.parse(process.env);

// backend/src/services/db.ts
import { Pool } from "pg";
var pool = env.DATABASE_URL ? new Pool({ connectionString: env.DATABASE_URL }) : null;
async function query(text, params = []) {
  if (!pool) {
    throw new Error(
      "Database is not configured. Set DATABASE_URL to use this service, or run without database-backed routes."
    );
  }
  const result = await pool.query(text, params);
  return result;
}

// backend/src/services/director/googleMedia.ts
import { GoogleGenAI } from "@google/genai";

// backend/src/services/director/budget.ts
var DEFAULT_DIRECTOR_BUDGET = Object.freeze({
  sceneAnchor: 1,
  primaryVideo: 1,
  automaticFallbackVideos: 0,
  automaticRepairPasses: 0
});
var DIRECTOR_CANARY_PRICING = Object.freeze({
  currency: "USD",
  effectiveDate: "2026-07-26",
  sceneAnchor1kOutputUsd: 0.067,
  primaryVideo720pPerSecondUsd: 0.1,
  primaryVideoDurationSeconds: 4,
  maximumInputAllowanceUsd: 0.01,
  source: "Google Gemini Developer API standard pricing"
});
function projectedDirectorPrimaryVideoCostUsd() {
  return Number((DIRECTOR_CANARY_PRICING.primaryVideo720pPerSecondUsd * DIRECTOR_CANARY_PRICING.primaryVideoDurationSeconds).toFixed(3));
}

// backend/src/services/director/quality.ts
import { z as z2 } from "zod";
var directorQualityScoreSchema = z2.object({
  playableVideo: z2.boolean(),
  identityConsistency: z2.number().min(0).max(100),
  promptAdherence: z2.number().min(0).max(100),
  motionStability: z2.number().min(0).max(100),
  anatomyQuality: z2.number().min(0).max(100),
  wardrobeContinuity: z2.number().min(0).max(100),
  visualArtifacts: z2.number().min(0).max(100),
  overallScore: z2.number().min(0).max(100),
  acceptable: z2.boolean(),
  localizedRepairIssue: z2.string().nullable(),
  failureCategories: z2.array(z2.enum([
    "not_playable",
    "identity_drift",
    "prompt_mismatch",
    "unstable_motion",
    "anatomy_defect",
    "wardrobe_discontinuity",
    "visual_artifact",
    "provider_moderation",
    "unknown"
  ]))
});

// backend/src/services/director/adapters.ts
var NANO_BANANA_2_MODEL = "gemini-3.1-flash-image";
var GEMINI_OMNI_FLASH_MODEL = "gemini-omni-flash-preview";
function sceneAnchorPrompt(plan) {
  return [
    "Create a provider-safe cinematic scene anchor for a clearly synthetic portrayal.",
    "Use the user-owned front reference only to preserve the planned cast identity.",
    "Do not present the result as a real photograph or documentary evidence.",
    `Synthetic disclosure: ${plan.syntheticDisclosure}.`,
    `Scene plan JSON: ${JSON.stringify(plan)}`
  ].join("\n");
}
function buildNanoBananaPayload(input) {
  if (!input.reference.ownershipConfirmed || input.reference.role !== "front_face") {
    throw new Error("Director scene anchors require one confirmed user-owned Front face reference.");
  }
  return {
    model: NANO_BANANA_2_MODEL,
    store: false,
    background: false,
    response_modalities: ["image"],
    input: [
      {
        type: "image",
        data: input.reference.data,
        mime_type: input.reference.mimeType
      },
      {
        type: "text",
        text: sceneAnchorPrompt(input.plan)
      }
    ],
    response_format: {
      type: "image",
      mime_type: "image/jpeg",
      aspect_ratio: input.aspectRatio ?? "9:16",
      image_size: "1K"
    }
  };
}
function primaryVideoPrompt(plan, shot, durationSeconds) {
  return [
    `Create exactly one ${durationSeconds}-second 720p video candidate in a single continuous shot.`,
    `Animate this synthetic cinematic scene: ${shot.summary}`,
    `Action: ${shot.action}`,
    `Camera: ${shot.cameraPlan}`,
    `Continuity: ${plan.continuityLocks.join("; ")}`,
    `Wardrobe: ${plan.wardrobe}`,
    `Environment: ${plan.environment}`,
    `Lighting: ${plan.lighting}`,
    "Keep movement natural, anatomy stable, and the portrayal clearly synthetic.",
    "No dialogue, music, ambient sound, or other audio."
  ].join("\n");
}
function buildOmniFlashPayload(input) {
  const shot = input.shot ?? input.plan.shots[0];
  if (!shot) throw new Error("Director primary video requires one planned shot.");
  const durationSeconds = input.durationSeconds ?? 4;
  return {
    model: GEMINI_OMNI_FLASH_MODEL,
    store: input.store ?? true,
    background: false,
    input: [
      {
        type: "image",
        data: input.anchor.data,
        mime_type: input.anchor.mimeType
      },
      {
        type: "text",
        text: primaryVideoPrompt(input.plan, shot, durationSeconds)
      }
    ],
    response_format: {
      type: "video",
      aspect_ratio: input.aspectRatio ?? "9:16",
      delivery: "uri"
    },
    generation_config: {
      video_config: {
        task: "image_to_video"
      }
    }
  };
}

// backend/src/services/director/contracts.ts
import { z as z3 } from "zod";
var compact = (value) => value.replace(/\s+/g, " ").trim();
var providerLeakPattern = /\b(?:nano banana|gemini omni|gemini|veo|seedance|firefly|replicate|provider payload|api error)\b/i;
var hiddenInstructionPattern = /\b(?:reference_images|previous_interaction_id|identity wrapper|continuity locks?|system prompt|provider)\b/i;
var directorShotSchema = z3.object({
  id: z3.string().min(1),
  summary: z3.string().min(1),
  action: z3.string().min(1),
  cameraPlan: z3.string().min(1),
  durationSeconds: z3.number().min(1).max(5)
});
var directorPlanSchema = z3.object({
  sceneSummary: z3.string().min(1),
  castDescription: z3.string().min(1),
  wardrobe: z3.string().min(1),
  environment: z3.string().min(1),
  lighting: z3.string().min(1),
  action: z3.string().min(1),
  cameraPlan: z3.string().min(1),
  continuityLocks: z3.array(z3.string().min(1)).min(1),
  publicCaption: z3.string().min(1).max(160),
  syntheticDisclosure: z3.literal("Synthetic portrayal"),
  shots: z3.array(directorShotSchema).min(1).max(3)
});
function sanitizeDirectorPublicCaption(value) {
  const firstSentence = compact(value).split(/[.!?]+/).map(compact).find((part) => part.length > 0 && !hiddenInstructionPattern.test(part));
  const caption = firstSentence ? `${firstSentence.replace(/[.?!]+$/g, "")}.` : "A cinematic scene is ready.";
  return caption.length <= 160 ? caption : `${caption.slice(0, 156).trimEnd()}...`;
}
function assertProviderNeutralPublicCaption(value) {
  const caption = sanitizeDirectorPublicCaption(value);
  if (providerLeakPattern.test(caption) || hiddenInstructionPattern.test(caption)) {
    return "A cinematic scene is ready.";
  }
  return caption;
}

// backend/src/services/director/progress.ts
var DIRECTOR_PROGRESS_STATES = [
  "Planning your scene",
  "Building the cast and setting",
  "Creating the shot",
  "Checking movement and continuity",
  "Polishing the result",
  "Saving to Drafts"
];

// backend/src/services/director/routing.ts
function selectDirectorRoute(input) {
  if (input.hasPersonalIdentityImage || input.intent === "personal_ai_cast") {
    return {
      route: "director_primary",
      automatic: false,
      seedanceInputMode: null,
      reason: "Personal AI Cast uses the Director anchor and primary-video pipeline only."
    };
  }
  if (["text_only", "establishing_shot", "synthetic_character"].includes(input.intent)) {
    return {
      route: "seedance_text_only",
      automatic: false,
      seedanceInputMode: "text_to_video",
      reason: "Seedance is retained only for text-only, establishing, or synthetic-character shots."
    };
  }
  if (["hero_shot", "extension", "first_last_frame"].includes(input.intent)) {
    return {
      route: "veo_specialist",
      automatic: false,
      seedanceInputMode: null,
      reason: "Veo remains an explicitly selected specialist route."
    };
  }
  return {
    route: "firefly_manual",
    automatic: false,
    seedanceInputMode: null,
    reason: "Still-image cleanup is reserved for a future explicitly selected specialist route."
  };
}

// backend/src/services/director/dryRunDiagnostics.ts
var DIRECTOR_DRY_RUN_SCENE = "She walks through a candlelit mansion and pauses after hearing a sound behind her.";
function buildLocalDryRunPlan(sceneIdea) {
  const scene = sceneIdea.replace(/\s+/g, " ").trim() || DIRECTOR_DRY_RUN_SCENE;
  return directorPlanSchema.parse({
    sceneSummary: scene,
    castDescription: "One adult synthetic cast member derived from one user-owned Front face reference.",
    wardrobe: "A continuity-locked evening outfit appropriate for the mansion setting.",
    environment: "A candlelit mansion interior with a quiet corridor and deep background shadows.",
    lighting: "Warm candlelight with controlled shadow detail and a soft edge light.",
    action: "Walk through the corridor, hear a sound from behind, pause, and listen.",
    cameraPlan: "One steady tracking move followed by a gentle hold when the cast member pauses.",
    continuityLocks: [
      "Preserve the same synthetic cast identity throughout.",
      "Keep wardrobe, candle direction, mansion geography, and screen direction continuous.",
      "Do not imply that the synthetic portrayal is a real photograph or recording."
    ],
    publicCaption: assertProviderNeutralPublicCaption(scene),
    syntheticDisclosure: "Synthetic portrayal",
    shots: [
      {
        id: "shot-1",
        summary: "The cast member walks into the candlelit corridor.",
        action: "Walk forward at a natural pace.",
        cameraPlan: "Steady medium tracking shot.",
        durationSeconds: 1.5
      },
      {
        id: "shot-2",
        summary: "A sound is heard from behind.",
        action: "Slow and begin to react without turning fully.",
        cameraPlan: "Continue the same tracking axis with no cut.",
        durationSeconds: 1.25
      },
      {
        id: "shot-3",
        summary: "The cast member pauses and listens.",
        action: "Hold a subtle alert expression and remain still.",
        cameraPlan: "Settle into a gentle locked hold.",
        durationSeconds: 1.25
      }
    ]
  });
}
function redactMediaData(payload) {
  return {
    ...payload,
    input: Array.isArray(payload.input) ? payload.input.map((part) => typeof part === "object" && part && "type" in part && part.type === "image" ? {
      type: "image",
      mime_type: "image/jpeg",
      data: "[redacted-reference-bytes]"
    } : part) : payload.input
  };
}
function buildDirectorProductionDryRun(sceneIdea = DIRECTOR_DRY_RUN_SCENE) {
  const plan = buildLocalDryRunPlan(sceneIdea);
  const reference = {
    data: "[redacted-reference-bytes]",
    mimeType: "image/jpeg",
    ownershipConfirmed: true,
    role: "front_face",
    hashPrefix: "[redacted]"
  };
  const anchorPayload = redactMediaData(buildNanoBananaPayload({
    reference,
    plan
  }));
  const omniPayload = redactMediaData(buildOmniFlashPayload({
    anchor: {
      data: "[redacted-scene-anchor-bytes]",
      mimeType: "image/jpeg"
    },
    plan,
    durationSeconds: DIRECTOR_CANARY_PRICING.primaryVideoDurationSeconds,
    aspectRatio: "9:16"
  }));
  const projectedVideoCost = projectedDirectorPrimaryVideoCostUsd();
  const projectedMaximumCostUsd = Number((DIRECTOR_CANARY_PRICING.sceneAnchor1kOutputUsd + projectedVideoCost + DIRECTOR_CANARY_PRICING.maximumInputAllowanceUsd).toFixed(3));
  const anchorPromptPart = Array.isArray(anchorPayload.input) ? anchorPayload.input[1] : null;
  const anchorPromptText = anchorPromptPart && typeof anchorPromptPart === "object" && "text" in anchorPromptPart && typeof anchorPromptPart.text === "string" ? anchorPromptPart.text : "";
  return {
    enabled: true,
    mode: "dry_run",
    paidExecutionEnabled: false,
    authorizationRecorded: false,
    providerSdkCallAllowed: false,
    plan,
    routing: selectDirectorRoute({
      intent: "personal_ai_cast",
      hasPersonalIdentityImage: true
    }),
    progressStates: [...DIRECTOR_PROGRESS_STATES],
    proposedProviderSequence: [
      { order: 1, role: "scene_anchor", requestCount: 1 },
      { order: 2, role: "primary_video", requestCount: 1 }
    ],
    proposedAnchorPayload: anchorPayload,
    proposedOmniPayload: omniPayload,
    projectedRequests: {
      sceneAnchor: 1,
      primaryVideo: 1,
      retry: 0,
      fallback: 0,
      repair: 0
    },
    actualTelemetry: {
      providerRequestCount: 0,
      providerRetryCount: 0,
      providerFallbackCount: 0,
      repairRequestCount: 0,
      billableMetric: null
    },
    projectedBudget: {
      ...DEFAULT_DIRECTOR_BUDGET,
      pricing: DIRECTOR_CANARY_PRICING,
      projectedMaximumCostUsd
    },
    disclosure: plan.syntheticDisclosure,
    publicCaption: plan.publicCaption,
    publicCaptionSeparated: plan.publicCaption !== anchorPromptText,
    secretsRedacted: true,
    privateUrlsRedacted: true
  };
}

// backend/src/services/productionHealthDiagnostics.ts
var requiredSeedanceReferenceRoles = [
  "front_angle",
  "full_body",
  "side_angle_left",
  "side_angle_right"
];
function nullableString(value) {
  return typeof value === "string" ? value : null;
}
function nullableNumber(value) {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}
function normalizeSupabaseReferenceRouteRow(row) {
  const notes = row.notes && typeof row.notes === "object" && !Array.isArray(row.notes) ? row.notes : {};
  return {
    provider: nullableString(row.provider),
    referenceRole: nullableString(row.reference_strategy),
    variant: nullableString(notes.variant),
    successCount: nullableNumber(row.success_count),
    failureCount: nullableNumber(row.failure_count),
    failureCategory: nullableString(row.last_failure_category)
  };
}
function isSeedanceProvider(provider) {
  return provider === "seedance-fast" || provider === "seedance-quality";
}
function buildSafeReferenceRouteReadiness(rows) {
  const routes = rows.map((row) => ({
    provider: row.provider,
    referenceRole: row.referenceRole,
    variant: row.variant,
    succeeded: (row.successCount ?? 0) > 0 && (row.successCount ?? 0) >= (row.failureCount ?? 0),
    failureCategory: row.failureCategory
  }));
  const knownSuccessfulReferenceRoutes = routes.filter((route) => route.succeeded);
  const knownBlockedReferenceRoutes = routes.filter((route) => !route.succeeded);
  const blockedReferenceRoles = Array.from(new Set(
    knownBlockedReferenceRoutes.filter((route) => isSeedanceProvider(route.provider)).map((route) => route.referenceRole).filter((role) => Boolean(role))
  ));
  const hasSeedanceModerationBlock = knownBlockedReferenceRoutes.some((route) => isSeedanceProvider(route.provider) && route.failureCategory === "reference_moderation_block");
  const seedanceImageReferenceBlocked = knownSuccessfulReferenceRoutes.length === 0 && hasSeedanceModerationBlock;
  const seedanceReferenceRoutesBlocked = knownSuccessfulReferenceRoutes.length === 0 && requiredSeedanceReferenceRoles.every((role) => blockedReferenceRoles.includes(role));
  const best = knownSuccessfulReferenceRoutes[0] ?? null;
  return {
    referenceRouteStatus: {
      state: best ? "succeeded" : knownBlockedReferenceRoutes.length ? "failed" : "unknown",
      referenceRole: best?.referenceRole ?? null,
      variant: best?.variant ?? null,
      failureCategory: knownBlockedReferenceRoutes[0]?.failureCategory ?? null,
      seedanceReferenceRoutesBlocked,
      blockedReferenceRoles,
      requiredReferenceRoles: [...requiredSeedanceReferenceRoles],
      knownSuccessfulReferenceRoutes,
      knownBlockedReferenceRoutes,
      allReferenceRouteResults: routes
    },
    seedanceImageReferenceBlocked
  };
}
async function fetchSafeReferenceRouteRowsFromSupabase({
  supabaseUrl,
  serviceRoleKey,
  fetchImpl = fetch
}) {
  const url = new URL("/rest/v1/render_success_memory", supabaseUrl);
  url.searchParams.set(
    "select",
    "provider,reference_strategy,notes,success_count,failure_count,last_failure_category"
  );
  url.searchParams.set("render_mode", "eq.reference_route_canary");
  url.searchParams.set("order", "updated_at.desc");
  url.searchParams.set("limit", "40");
  const response = await fetchImpl(url, {
    method: "GET",
    headers: {
      apikey: serviceRoleKey,
      Authorization: `Bearer ${serviceRoleKey}`,
      Accept: "application/json"
    },
    signal: AbortSignal.timeout(5e3)
  });
  if (!response.ok) {
    throw new Error("Supabase readiness query failed.");
  }
  const payload = await response.json();
  if (!Array.isArray(payload)) {
    throw new Error("Supabase readiness query returned an invalid response.");
  }
  return payload.map((row) => normalizeSupabaseReferenceRouteRow(
    row && typeof row === "object" && !Array.isArray(row) ? row : {}
  ));
}
async function readSafeReferenceRouteReadiness() {
  if (!env.DATABASE_URL && env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY) {
    const rows = await fetchSafeReferenceRouteRowsFromSupabase({
      supabaseUrl: env.SUPABASE_URL,
      serviceRoleKey: env.SUPABASE_SERVICE_ROLE_KEY
    });
    return buildSafeReferenceRouteReadiness(rows);
  }
  const result = await query(
    `select
       provider,
       reference_strategy as "referenceRole",
       notes->>'variant' as "variant",
       success_count as "successCount",
       failure_count as "failureCount",
       last_failure_category as "failureCategory"
     from render_success_memory
     where render_mode = 'reference_route_canary'
     order by greatest(
       coalesce(last_success_at, '-infinity'::timestamptz),
       coalesce(last_failure_at, '-infinity'::timestamptz),
       updated_at
     ) desc
     limit 40`
  );
  return buildSafeReferenceRouteReadiness(result.rows);
}
function generationProviders() {
  const replicateReady = Boolean(env.REPLICATE_API_TOKEN);
  const klingReady = Boolean(
    env.KLING_ENABLED && env.KLING_REFERENCE_MODEL && (env.FAL_KEY || env.KLING_API_KEY)
  );
  return [
    {
      id: "seedance-2.0",
      ready: replicateReady,
      status: replicateReady ? "ready" : "not_configured"
    },
    {
      id: "seedance-quality",
      ready: replicateReady,
      status: replicateReady ? "ready" : "not_configured"
    },
    {
      id: "kling-reference-beta",
      ready: klingReady,
      status: klingReady ? "ready" : "not_configured"
    },
    {
      id: "demo-mode",
      ready: true,
      status: "ready"
    }
  ];
}
async function buildProductionHealthDiagnostics() {
  const checkedAt = (/* @__PURE__ */ new Date()).toISOString();
  const providers = generationProviders();
  const director = buildDirectorProductionDryRun();
  try {
    const readiness = await readSafeReferenceRouteReadiness();
    return {
      service: "lumora-vercel-api",
      checkedAt,
      ok: providers.some((provider) => provider.id === "seedance-2.0" && provider.ready),
      mode: process.env.NODE_ENV ?? "production",
      configured: {
        database: Boolean(env.DATABASE_URL),
        supabaseAdmin: Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY),
        replicate: Boolean(env.REPLICATE_API_TOKEN)
      },
      missingRequired: env.REPLICATE_API_TOKEN ? [] : ["REPLICATE_API_TOKEN"],
      missingRecommended: env.REPLICATE_API_TOKEN ? [] : ["REPLICATE_API_TOKEN"],
      generationProviders: providers,
      database: {
        ok: true,
        serviceRoleConfigured: Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY),
        tables: [],
        schemaChecks: []
      },
      ...readiness,
      director,
      secretsRedacted: true,
      privateUrlsRedacted: true
    };
  } catch {
    return {
      service: "lumora-vercel-api",
      checkedAt,
      ok: false,
      mode: process.env.NODE_ENV ?? "production",
      configured: {
        database: Boolean(env.DATABASE_URL),
        supabaseAdmin: Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY),
        replicate: Boolean(env.REPLICATE_API_TOKEN)
      },
      missingRequired: env.REPLICATE_API_TOKEN ? [] : ["REPLICATE_API_TOKEN"],
      missingRecommended: ["Reference-route readiness unavailable"],
      generationProviders: providers,
      database: {
        ok: false,
        serviceRoleConfigured: Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY),
        tables: [],
        schemaChecks: []
      },
      ...buildSafeReferenceRouteReadiness([]),
      director,
      diagnosticsError: {
        ok: false,
        key: "referenceRouteStatus",
        message: "Reference-route readiness is temporarily unavailable."
      },
      secretsRedacted: true,
      privateUrlsRedacted: true
    };
  }
}

// serverless/entries/health-diagnostics.ts
function sendJson(res, statusCode, payload) {
  res.statusCode = statusCode;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify(payload));
}
async function handler(req, res) {
  if ((req.method ?? "GET").toUpperCase() !== "GET") {
    return sendJson(res, 405, {
      ok: false,
      error: "method_not_allowed",
      secretsRedacted: true,
      privateUrlsRedacted: true
    });
  }
  return sendJson(res, 200, await buildProductionHealthDiagnostics());
}
export {
  handler as default
};
