// Generated by scripts/build-vercel-api.mjs. Do not edit by hand.

// backend/src/lib/env.ts
import "dotenv/config";
import { z } from "zod";
var booleanEnv = z.preprocess((value) => {
  if (typeof value === "boolean") return value;
  if (typeof value === "number") return value === 1;
  if (typeof value === "string") {
    const normalized = value.trim().toLowerCase();
    if (["1", "true", "yes", "y", "on"].includes(normalized)) return true;
    if (["0", "false", "no", "n", "off", ""].includes(normalized)) return false;
  }
  return value;
}, z.boolean());
var envSchema = z.object({
  API_PORT: z.coerce.number().default(8787),
  APP_URL: z.string().url().default("http://localhost:4173"),
  WEB_ORIGIN: z.string().optional(),
  DEMO_MODE: booleanEnv.default(false),
  BILLING_ENABLED: booleanEnv.default(false),
  REQUIRE_STRIPE: booleanEnv.default(false),
  SUPABASE_URL: z.string().url().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(1).optional(),
  SUPABASE_JWT_SECRET: z.string().min(1).optional(),
  DATABASE_URL: z.string().min(1).optional(),
  REDIS_URL: z.string().min(1).optional(),
  STRIPE_SECRET_KEY: z.string().min(1).optional(),
  STRIPE_WEBHOOK_SECRET: z.string().min(1).optional(),
  OPENAI_API_KEY: z.string().min(1).optional(),
  OPENAI_MODEL: z.string().min(1).optional(),
  OPENAI_CHAT_MODEL: z.string().min(1).optional(),
  OPENAI_IMAGE_MODEL: z.string().default("gpt-image-1"),
  OPENAI_VIDEO_ENABLED: booleanEnv.default(false),
  OPENAI_VIDEO_MODEL: z.string().default("sora-2"),
  OPENAI_VIDEO_CHARACTER_ENABLED: booleanEnv.default(false),
  OPENAI_VIDEO_SIZE: z.string().default("720x1280"),
  OPENAI_VIDEO_SECONDS: z.coerce.number().int().refine((value) => [4, 8, 12].includes(value), {
    message: "OPENAI_VIDEO_SECONDS must be 4, 8, or 12."
  }).default(4),
  DEBUG_PROVIDER_PROMPTS: booleanEnv.default(false),
  GOOGLE_API_KEY: z.string().min(1).optional(),
  FAL_ADMIN_KEY: z.string().min(1).optional(),
  FAL_KEY: z.string().min(1).optional(),
  KLING_ENABLED: booleanEnv.default(false),
  KLING_PROVIDER: z.string().default("fal"),
  KLING_API_KEY: z.string().min(1).optional(),
  KLING_MODEL: z.string().min(1).optional(),
  KLING_REFERENCE_MODEL: z.string().min(1).default("fal-ai/kling-video/o1/standard/reference-to-video"),
  KLING_ELEMENTS_MODEL: z.string().min(1).optional(),
  KLING_SCENE_ANCHOR_VIDEO_MODEL: z.string().min(1).optional(),
  SCENE_ANCHOR_ENABLED: booleanEnv.default(false),
  SCENE_ANCHOR_PROVIDER: z.string().default("fal"),
  SCENE_ANCHOR_MODEL: z.string().min(1).optional(),
  SCENE_ANCHOR_FALLBACK_MODE: z.string().default("pause"),
  RUNWAY_ENABLED: booleanEnv.default(false),
  RUNWAY_API_KEY: z.string().min(1).optional(),
  RUNWAY_MODEL: z.string().min(1).optional(),
  RUNWAY_REFERENCE_MODEL: z.string().min(1).optional(),
  REPLICATE_API_TOKEN: z.string().min(1).optional(),
  REPLICATE_WEBHOOK_SECRET: z.string().min(1).optional(),
  RENDER_SUCCESS_MAX_PAID_ATTEMPTS: z.coerce.number().int().min(1).max(5).default(3),
  RENDER_SUCCESS_AUTO_RETRY: booleanEnv.default(true),
  ENABLE_RENDER_PROBE: booleanEnv.default(false),
  RESEND_API_KEY: z.string().min(1).optional(),
  NOTIFICATION_FROM: z.string().email().default("alerts@example.com")
});
var env = envSchema.parse(process.env);

// backend/src/services/db.ts
import { Pool } from "pg";
var pool = env.DATABASE_URL ? new Pool({ connectionString: env.DATABASE_URL }) : null;
async function query(text, params = []) {
  if (!pool) {
    throw new Error(
      "Database is not configured. Set DATABASE_URL to use this service, or run without database-backed routes."
    );
  }
  const result = await pool.query(text, params);
  return result;
}

// backend/src/services/productionHealthDiagnostics.ts
var requiredSeedanceReferenceRoles = [
  "front_angle",
  "full_body",
  "side_angle_left",
  "side_angle_right"
];
function nullableString(value) {
  return typeof value === "string" ? value : null;
}
function nullableNumber(value) {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}
function normalizeSupabaseReferenceRouteRow(row) {
  const notes = row.notes && typeof row.notes === "object" && !Array.isArray(row.notes) ? row.notes : {};
  return {
    provider: nullableString(row.provider),
    referenceRole: nullableString(row.reference_strategy),
    variant: nullableString(notes.variant),
    successCount: nullableNumber(row.success_count),
    failureCount: nullableNumber(row.failure_count),
    failureCategory: nullableString(row.last_failure_category)
  };
}
function isSeedanceProvider(provider) {
  return provider === "seedance-fast" || provider === "seedance-quality";
}
function buildSafeReferenceRouteReadiness(rows) {
  const routes = rows.map((row) => ({
    provider: row.provider,
    referenceRole: row.referenceRole,
    variant: row.variant,
    succeeded: (row.successCount ?? 0) > 0 && (row.successCount ?? 0) >= (row.failureCount ?? 0),
    failureCategory: row.failureCategory
  }));
  const knownSuccessfulReferenceRoutes = routes.filter((route) => route.succeeded);
  const knownBlockedReferenceRoutes = routes.filter((route) => !route.succeeded);
  const blockedReferenceRoles = Array.from(new Set(
    knownBlockedReferenceRoutes.filter((route) => isSeedanceProvider(route.provider)).map((route) => route.referenceRole).filter((role) => Boolean(role))
  ));
  const hasSeedanceModerationBlock = knownBlockedReferenceRoutes.some((route) => isSeedanceProvider(route.provider) && route.failureCategory === "reference_moderation_block");
  const seedanceImageReferenceBlocked = knownSuccessfulReferenceRoutes.length === 0 && hasSeedanceModerationBlock;
  const seedanceReferenceRoutesBlocked = knownSuccessfulReferenceRoutes.length === 0 && requiredSeedanceReferenceRoles.every((role) => blockedReferenceRoles.includes(role));
  const best = knownSuccessfulReferenceRoutes[0] ?? null;
  return {
    referenceRouteStatus: {
      state: best ? "succeeded" : knownBlockedReferenceRoutes.length ? "failed" : "unknown",
      referenceRole: best?.referenceRole ?? null,
      variant: best?.variant ?? null,
      failureCategory: knownBlockedReferenceRoutes[0]?.failureCategory ?? null,
      seedanceReferenceRoutesBlocked,
      blockedReferenceRoles,
      requiredReferenceRoles: [...requiredSeedanceReferenceRoles],
      knownSuccessfulReferenceRoutes,
      knownBlockedReferenceRoutes,
      allReferenceRouteResults: routes
    },
    seedanceImageReferenceBlocked
  };
}
async function fetchSafeReferenceRouteRowsFromSupabase({
  supabaseUrl,
  serviceRoleKey,
  fetchImpl = fetch
}) {
  const url = new URL("/rest/v1/render_success_memory", supabaseUrl);
  url.searchParams.set(
    "select",
    "provider,reference_strategy,notes,success_count,failure_count,last_failure_category"
  );
  url.searchParams.set("render_mode", "eq.reference_route_canary");
  url.searchParams.set("order", "updated_at.desc");
  url.searchParams.set("limit", "40");
  const response = await fetchImpl(url, {
    method: "GET",
    headers: {
      apikey: serviceRoleKey,
      Authorization: `Bearer ${serviceRoleKey}`,
      Accept: "application/json"
    },
    signal: AbortSignal.timeout(5e3)
  });
  if (!response.ok) {
    throw new Error("Supabase readiness query failed.");
  }
  const payload = await response.json();
  if (!Array.isArray(payload)) {
    throw new Error("Supabase readiness query returned an invalid response.");
  }
  return payload.map((row) => normalizeSupabaseReferenceRouteRow(
    row && typeof row === "object" && !Array.isArray(row) ? row : {}
  ));
}
async function readSafeReferenceRouteReadiness() {
  if (!env.DATABASE_URL && env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY) {
    const rows = await fetchSafeReferenceRouteRowsFromSupabase({
      supabaseUrl: env.SUPABASE_URL,
      serviceRoleKey: env.SUPABASE_SERVICE_ROLE_KEY
    });
    return buildSafeReferenceRouteReadiness(rows);
  }
  const result = await query(
    `select
       provider,
       reference_strategy as "referenceRole",
       notes->>'variant' as "variant",
       success_count as "successCount",
       failure_count as "failureCount",
       last_failure_category as "failureCategory"
     from render_success_memory
     where render_mode = 'reference_route_canary'
     order by greatest(
       coalesce(last_success_at, '-infinity'::timestamptz),
       coalesce(last_failure_at, '-infinity'::timestamptz),
       updated_at
     ) desc
     limit 40`
  );
  return buildSafeReferenceRouteReadiness(result.rows);
}
function generationProviders() {
  const replicateReady = Boolean(env.REPLICATE_API_TOKEN);
  const klingReady = Boolean(
    env.KLING_ENABLED && env.KLING_REFERENCE_MODEL && (env.FAL_KEY || env.KLING_API_KEY)
  );
  return [
    {
      id: "seedance-2.0",
      ready: replicateReady,
      status: replicateReady ? "ready" : "not_configured"
    },
    {
      id: "seedance-quality",
      ready: replicateReady,
      status: replicateReady ? "ready" : "not_configured"
    },
    {
      id: "kling-reference-beta",
      ready: klingReady,
      status: klingReady ? "ready" : "not_configured"
    },
    {
      id: "demo-mode",
      ready: true,
      status: "ready"
    }
  ];
}
async function buildProductionHealthDiagnostics() {
  const checkedAt = (/* @__PURE__ */ new Date()).toISOString();
  const providers = generationProviders();
  try {
    const readiness = await readSafeReferenceRouteReadiness();
    return {
      service: "lumora-vercel-api",
      checkedAt,
      ok: providers.some((provider) => provider.id === "seedance-2.0" && provider.ready),
      mode: process.env.NODE_ENV ?? "production",
      configured: {
        database: Boolean(env.DATABASE_URL),
        supabaseAdmin: Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY),
        replicate: Boolean(env.REPLICATE_API_TOKEN)
      },
      missingRequired: env.REPLICATE_API_TOKEN ? [] : ["REPLICATE_API_TOKEN"],
      missingRecommended: env.REPLICATE_API_TOKEN ? [] : ["REPLICATE_API_TOKEN"],
      generationProviders: providers,
      database: {
        ok: true,
        serviceRoleConfigured: Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY),
        tables: [],
        schemaChecks: []
      },
      ...readiness,
      secretsRedacted: true,
      privateUrlsRedacted: true
    };
  } catch {
    return {
      service: "lumora-vercel-api",
      checkedAt,
      ok: false,
      mode: process.env.NODE_ENV ?? "production",
      configured: {
        database: Boolean(env.DATABASE_URL),
        supabaseAdmin: Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY),
        replicate: Boolean(env.REPLICATE_API_TOKEN)
      },
      missingRequired: env.REPLICATE_API_TOKEN ? [] : ["REPLICATE_API_TOKEN"],
      missingRecommended: ["Reference-route readiness unavailable"],
      generationProviders: providers,
      database: {
        ok: false,
        serviceRoleConfigured: Boolean(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY),
        tables: [],
        schemaChecks: []
      },
      ...buildSafeReferenceRouteReadiness([]),
      diagnosticsError: {
        ok: false,
        key: "referenceRouteStatus",
        message: "Reference-route readiness is temporarily unavailable."
      },
      secretsRedacted: true,
      privateUrlsRedacted: true
    };
  }
}

// serverless/entries/health-diagnostics.ts
function sendJson(res, statusCode, payload) {
  res.statusCode = statusCode;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify(payload));
}
async function handler(req, res) {
  if ((req.method ?? "GET").toUpperCase() !== "GET") {
    return sendJson(res, 405, {
      ok: false,
      error: "method_not_allowed",
      secretsRedacted: true,
      privateUrlsRedacted: true
    });
  }
  return sendJson(res, 200, await buildProductionHealthDiagnostics());
}
export {
  handler as default
};
